maintainer       "mconf"
maintainer_email "mconf@mconf.org"
license          "GPL v3"
description      "Installs/Configures a mconf-node"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
supports         "ubuntu", "= 10.04"
depends          "mconf-bbb"
depends          "mconf-monitor"
depends          "apt"
